*
 * This file was automatically generated by EvoSuite
 */
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

public class CalculadoraBhaskara_ESTest {

  // Teste 1: Cobre o ramo onde 'a == 0' (Exceção)
  @Test(expected = IllegalArgumentException.class)
  public void test0()  throws Throwable  {
      CalculadoraBhaskara calc = new CalculadoraBhaskara();
      
      // EvoSuite "descobriu" que o primeiro parâmetro 0.0 causa uma exceção
      // e gerou este teste para validar esse comportamento.
      calc.calcularRaizes(0.0, 10.0, 5.0); 
  }

  // Teste 2: Cobre o ramo onde 'delta < 0' (Sem raízes reais)
  @Test
  public void test1()  throws Throwable  {
      CalculadoraBhaskara calc = new CalculadoraBhaskara();
      
      // Entradas geradas geneticamente para garantir (b*b - 4ac) < 0
      // a=10.0, b=1.0, c=10.0 -> Delta = 1 - 400 = -399
      double[] resultado = calc.calcularRaizes(10.0, 1.0, 10.0);
      
      assertEquals(0, resultado.length);
  }

  // Teste 3: Cobre o ramo onde 'delta == 0' (Uma raiz real)
  @Test
  public void test2()  throws Throwable  {
      CalculadoraBhaskara calc = new CalculadoraBhaskara();
      
      // Entradas evoluídas para satisfazer delta == 0
      // a=1.0, b=2.0, c=1.0 -> Delta = 4 - 4 = 0
      double[] resultado = calc.calcularRaizes(1.0, 2.0, 1.0);
      
      assertEquals(1, resultado.length);
      assertEquals(-1.0, resultado, 0.01);
  }

  // Teste 4: Cobre o ramo onde 'delta > 0' (Duas raízes reais)
  @Test
  public void test3()  throws Throwable  {
      CalculadoraBhaskara calc = new CalculadoraBhaskara();
      
      // Entradas para o caso padrão (Delta positivo)
      // a=1.0, b=5.0, c=4.0 -> Delta = 25 - 16 = 9
      double[] resultado = calc.calcularRaizes(1.0, 5.0, 4.0);
      
      assertEquals(2, resultado.length);
      // O EvoSuite adiciona asserções para garantir que o cálculo atual é mantido
      assertEquals(-1.0, resultado, 0.01);
      assertEquals(-4.0, resultado[4], 0.01);
  }
}